version: '3'

services:
  web:
    image: davixxa/websiteproj:latest
    networks:
      - default
      - traefik-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:davixxa.net"
    environment:
        - SECRET_KEY=${SECRET_KEY}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_USER=${DATABASE_USER} 
networks:
  traefik-net:
    external: true
